# Generated by Django 4.2.4 on 2023-08-31 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pagamento_intent',
            new_name='payment_intent',
        ),
    ]
